before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_USER=travis"
  - "npm install -g grunt-cli"

install:
  - "npm install"

script:
  - "grunt all"

env:
  - DB=mysql DIALECT=mysql
  - DB=mysql DIALECT=postgres
  - DB=mysql DIALECT=postgres-native
  - DB=mysql DIALECT=sqlite
  - DB=mysql DIALECT=mariadb

matrix:
  fast_finish: true

language: node_js

node_js:
  - "4.2"

branches:
  only:
    - master
    - dev

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.3"
